markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
title: Zhang Chao's Blog
description: Zhang Chao's Blog, powered by Jekyll...
feed: 

author: Zhang Chao

seo: 
  keyword: 
  description: 
config:
  js_dir:
  img_dir:
  css_dir:
